### ISSUE TITLE
Evaluate whether it is more convenient to use a configuration file system for the `Task` class

### ISSUE THREAD

**Issue by gcroci2** [ANNUBS/annubes#36]
The `Task` class takes as input > 10 parameters. We will evaluate if the package of configuration management [Dynaconf](https://www.dynaconf.com/) can help in the setting of the many `Task` class' parameters. 

By using Dynaconf, the loaded config (which is a variable) is importable and thus can be accessed across different functions/classes/modules without passing it as a parameter (Detail see example [Using Python Only](https://dynaconf.com/#initialize-dynaconf-on-your-project)).

**Comment by DaniBodor** [comment]
https://github.com/ANNUBS/annubes/pull/37#issue-2146219429:

> Thinking about it, I am not convinced. It makes no sense to create a class whose only function is to create a few attributes in the init, and from what I understand this would be the case. Maybe a dictionary passed to the Task class would be more than enough for this case. I also opened an issue (https://github.com/ANNUBS/annubes/issues/36) for evaluating Dynaconf - The configuration management package, which I still think is the best way to go.
> Thoughts? @DaniBodor

I agree that a settings dictionary could be a simpler way of doing it compared to a dedicated class. On the other hand, [dataclasses do offer a bunch of advantages over dictionaries](https://medium.com/prodigy-engineering/python-from-dictionaries-to-data-classes-b1698a366e6d). For example, it would be a bit convoluted to create a dictionary where some values are explicitly given by the user and others loaded from default. Other things that would be funky is type hinting the dictionary. 
In the end, the dataclass can easily be loaded into `Task` as a dictionary (which I agree would be the way to go) using `vars(TaskSettings)` (or whatever the name of that dataclass would be).

All that being said, if there's a better way of doing it, I'm all for it!

I don't know the Dynaconf package, but if you think it's a robust system and a better way to store the settings then let's do it that way. The only usage of configuration files I have seen in the past were very ad hoc and error prone, but if that is not the case with this system then let's go for it.

Ultimately, this might be a thing where we try both ways and see which one we think is better in practice rather than theorizing about it for a long time. If you want we can divide it up, where one of us does Dynaconf and the other does dict/dataclass.

Let me know what you think.

**Comment by gcroci2** [comment]
Okay let's proceed with the dataclass option for now, which is the fastest, and let's keep this issue for the future. In the meantime, I'll understand better how Dynaconf works in the NPLinker project, and then I will have a better idea if it can work for us as well.

**Comment by gcroci2** [comment]
We've decided to implement the functionalities originally planned for the `annubes` package within the [NeuroGym](https://github.com/neurogym/neurogym) package instead, which represents the current state-of-the-art. For now, this is not relevant anymore. In case we will open the issue again.
